import {render,validateEdition,config} from './render.mjs';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const now=new Date().toISOString();
const e={date:now.slice(0,10),researchedAt:now,reviewComplete:true,sections:config.sections.map((title,i)=>({title,deck:'Test fixture, not news',stories:Array.from({length:config.sectionRules[title].target},(_,j)=>({eventId:`test-${i}-${j}`,category:'Test',headline:`Fixture story ${i} ${j}`,summary:'Synthetic test only.',publishedAt:now,sources:[{url:`https://source-a-${i}.example/${j}`,label:'Test source A',verifiedAt:now},{url:`https://source-b-${i}.example/${j}`,label:'Test source B',verifiedAt:now}]}))})),metrics:config.metrics.map(label=>({label,value:'Source unavailable',asOf:'Test only',source:'https://example.com/metric'})),marketAnalysis:'Synthetic test, not a market claim.',marketAnalysisSources:[],earnings:{items:[],emptyReason:'Test only'}};
const prices={generatedAt:now,rows:Array.from({length:24},(_,i)=>({symbol:`TEST${i}`,name:'Fixture',exchange:'Test',currency:'USD',price:10+i,week:i<12?i+1:-i,month:-i,asOf:e.date,quoteUrl:`https://example.com/quote/${i}`}))};
const out=await fs.mkdtemp(path.join(os.tmpdir(),'daybreak-test-'));
const result=await render(e,prices,prices,out);
const validation=execFileSync('python3',[new URL('./validate_html.py',import.meta.url).pathname,out,result.archive],{encoding:'utf8'});
assert((await fs.readFile(path.join(out,result.archive))).equals(await fs.readFile(path.join(out,'daybreak-latest.html'))));
const belowTarget=structuredClone(e);belowTarget.sections[0].stories=[];belowTarget.sections[0].emptyReason='No additional story passed verification.';
validateEdition(belowTarget);await render(belowTarget,prices,prices,out);
assert((await fs.readFile(path.join(out,result.archive),'utf8')).includes('Editorial target: 5; 0 fresh stories met the sourcing standard'));
const duplicate=structuredClone(e);duplicate.sections[1].stories[0].eventId='test-0-0';assert.throws(()=>validateEdition(duplicate),/Duplicate/);
const badUrl=structuredClone(e);badUrl.sections[0].stories[0].sources[0].url='javascript:alert(1)';assert.throws(()=>validateEdition(badUrl));
const sparse={...prices,rows:prices.rows.map(x=>({...x,week:-1}))};await render(e,sparse,prices,out);assert((await fs.readFile(path.join(out,result.archive),'utf8')).includes('No additional eligible stock'));
console.log('PASS: render, soft editorial targets, balanced HTML, section order, table counts, checksums, duplicate rejection, URL rejection and unavailable slots');
console.log(validation.trim());
