"""
Generates data/news.json for the "Today's News" page — one Morning
Intelligence Edition per run.

What this does, in order:
  1. Look up when the last successful edition ran (state.py) — or fall
     back to the last 3 days if this is the first run ever.
  2. For each text-based section in config.TEXT_SECTIONS, ask Claude to
     research it via web search and write it up (claude_news.py).
  3. Carry the Money/Markets section forward unchanged — it needs a real
     market-data API, not LLM research, and isn't wired up yet.
  4. Write the result to data/news.json (same schema news.js already
     expects — no frontend changes needed).
  5. Record this run as the new "last successful" timestamp.

Run manually:
    cd backend
    python generate_news.py

Requires ANTHROPIC_API_KEY to be set (see .env.example).
"""

import argparse
import json
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, str(Path(__file__).resolve().parent))

from config import AI_PROVIDER, TEXT_SECTIONS
import state

if AI_PROVIDER == "openai":
    from openai_news import research_section
else:
    from claude_news import research_section

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
NEWS_JSON_PATH = DATA_DIR / "news.json"

# Money/Markets isn't AI-generated yet — see README "Roadmap" for why.
# Carried forward as-is so the page still has a Money/Markets tab.
MARKETS_PLACEHOLDER = {
    "id": "money-markets",
    "label": "Money / Markets",
    "kicker": "Indices, rates and earnings",
    "stories": [
        {
            "category": "Pending",
            "headline": "Money/Markets isn't wired up yet",
            "summary": (
                "This section needs a real market-data API (for accurate, "
                "timestamped prices) rather than AI-generated research, so "
                "it's a separate build phase. See the project README."
            ),
            "sources": [],
        }
    ],
}

# Stats bar placeholders — real values arrive once Money/Markets (above) is built.
STATS_PLACEHOLDER = [
    {"label": "Sample Metric 1", "value": "--", "note": "Placeholder"},
    {"label": "Sample Metric 2", "value": "--", "note": "Placeholder"},
    {"label": "Sample Metric 3", "value": "--", "note": "Placeholder"},
    {"label": "Sample Metric 4", "value": "--", "note": "Placeholder"},
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--since-days",
        type=int,
        default=None,
        help=(
            "Ignore state.json and search back this many days instead. "
            "Use this when manually re-running/testing — otherwise each "
            "re-run narrows the window to 'since the last run a few "
            "minutes ago', which tends to legitimately find nothing."
        ),
    )
    parser.add_argument(
        "--only",
        type=str,
        default=None,
        metavar="SECTION_ID",
        help=(
            "Research only this one section (e.g. --only top-news) and "
            "print the result — does NOT write data/news.json or advance "
            "state.json. Use this to cheaply test a provider/model change "
            "before running (and paying for) all sections."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    since_iso = state.load_since(force_lookback_days=args.since_days)
    print(f"Searching for news since {since_iso}\n")

    if args.only:
        section = next((s for s in TEXT_SECTIONS if s.id == args.only), None)
        if section is None:
            valid_ids = ", ".join(s.id for s in TEXT_SECTIONS)
            print(f"Unknown section id {args.only!r}. Valid ids: {valid_ids}")
            return
        print(f"[TEST MODE] Researching only: {section.label}...")
        stories = research_section(section, since_iso)
        print(f"\n-> {len(stories)} stories:\n")
        print(json.dumps(stories, indent=2))
        print("\n(--only mode: data/news.json and state.json were NOT touched)")
        return

    sections_out = []
    total_stories = 0
    for section in TEXT_SECTIONS:
        print(f"Researching: {section.label}...")
        stories = research_section(section, since_iso)
        print(f"  -> {len(stories)} stories")
        total_stories += len(stories)
        sections_out.append(
            {
                "id": section.id,
                "label": section.label,
                "kicker": section.kicker,
                "stories": stories,
            }
        )

    sections_out.append(MARKETS_PLACEHOLDER)

    output = {
        "_comment": "Generated by backend/generate_news.py. Do not edit by hand.",
        "stats": STATS_PLACEHOLDER,
        "sections": sections_out,
    }

    DATA_DIR.mkdir(exist_ok=True)
    NEWS_JSON_PATH.write_text(json.dumps(output, indent=2))
    print(f"\nWrote {NEWS_JSON_PATH} ({total_stories} stories total)")

    if total_stories == 0:
        print(
            "\nWARNING: every section came back empty. NOT advancing "
            "state.json's timestamp — next run will retry the same window "
            "instead of narrowing it further. If this keeps happening, "
            "re-run with a wider window, e.g.:\n"
            "  python generate_news.py --since-days 3"
        )
        return

    state.save_success()
    print("Updated state.json with this run's timestamp.")


if __name__ == "__main__":
    main()
