import {render,validateAudit,validateEdition,config,editionDigest,sourceRosters} from './render.mjs';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const now=new Date().toISOString();
const e={date:now.slice(0,10),researchedAt:now,reviewComplete:true,sections:config.sections.map((title,i)=>({title,deck:'Test fixture, not news',stories:Array.from({length:config.sectionRules[title].target},(_,j)=>({eventId:`test-${i}-${j}`,category:'Test',headline:`Fixture story ${i} ${j}`,summary:'Synthetic test only.',publishedAt:now,sources:[{url:`https://source-a-${i}.example/${j}`,label:'Test source A',verifiedAt:now},{url:`https://source-b-${i}.example/${j}`,label:'Test source B',verifiedAt:now}]}))})),metrics:config.metrics.map(label=>({label,value:'Source unavailable',asOf:'Test only',source:'https://example.com/metric'})),marketAnalysis:'Synthetic test, not a market claim.',marketAnalysisSources:[],earnings:{items:[],emptyReason:'Test only'}};
const makeAudit=edition=>({date:edition.date,researchedAt:edition.researchedAt,editionSha256:editionDigest(edition),sections:config.sections.map((title,i)=>({title,sources:sourceRosters.get(title.toLowerCase().replace(/[^a-z0-9]+/g,'')).map(source=>({rosterUrl:source.url,status:'reviewed',checkedAt:now,note:'',articleUrls:[source.url]})),supplementalArticleUrls:edition.sections[i].stories.flatMap(story=>story.sources.map(source=>source.url))}))});
const audit=makeAudit(e);
const prices={generatedAt:now,rows:Array.from({length:24},(_,i)=>({symbol:`TEST${i}`,name:'Fixture',exchange:'Test',currency:'USD',price:10+i,week:i<12?i+1:-i,month:-i,asOf:e.date,quoteUrl:`https://example.com/quote/${i}`}))};
const out=await fs.mkdtemp(path.join(os.tmpdir(),'daybreak-test-'));
const result=await render(e,prices,prices,out,audit);
const validation=execFileSync('python3',[new URL('./validate_html.py',import.meta.url).pathname,out,result.archive],{encoding:'utf8'});
assert((await fs.readFile(path.join(out,result.archive))).equals(await fs.readFile(path.join(out,'daybreak-latest.html'))));
const rendered=await fs.readFile(path.join(out,result.archive),'utf8');
assert(rendered.includes('Research source audit:'));assert(rendered.includes('BBC News'));assert(rendered.includes('(reviewed)'));assert(rendered.includes('Spectrum — Autism Research News'));
const belowTarget=structuredClone(e);belowTarget.sections[0].stories=[];belowTarget.sections[0].emptyReason='No additional story passed verification.';
validateEdition(belowTarget);await render(belowTarget,prices,prices,out,makeAudit(belowTarget));
assert(!(await fs.readFile(path.join(out,result.archive),'utf8')).includes('Editorial target:'));
await assert.rejects(render(e,prices,prices,out),/Research audit/);
const tampered=structuredClone(audit);tampered.editionSha256='0'.repeat(64);assert.throws(()=>validateAudit(tampered,e),/does not match/);
const incomplete=structuredClone(audit);incomplete.sections[0].sources.pop();assert.throws(()=>validateAudit(incomplete,e),/roster incomplete/);
const stale=structuredClone(audit);stale.sections[0].sources[0].checkedAt='2020-01-01T00:00:00Z';assert.throws(()=>validateAudit(stale,e),/Stale research audit/);
const missingPublishedSource=structuredClone(audit);missingPublishedSource.sections[0].supplementalArticleUrls=[];assert.throws(()=>validateAudit(missingPublishedSource,e),/Published source absent/);
const duplicate=structuredClone(e);duplicate.sections[1].stories[0].eventId='test-0-0';assert.throws(()=>validateEdition(duplicate),/Duplicate/);
const sharedEvidence=structuredClone(e);sharedEvidence.sections[1].stories[0].sources=structuredClone(sharedEvidence.sections[0].stories[0].sources);validateEdition(sharedEvidence);
const badUrl=structuredClone(e);badUrl.sections[0].stories[0].sources[0].url='javascript:alert(1)';assert.throws(()=>validateEdition(badUrl));
const sparse={...prices,rows:prices.rows.map(x=>({...x,week:-1}))};await render(e,sparse,prices,out,audit);assert((await fs.readFile(path.join(out,result.archive),'utf8')).includes('No additional eligible stock'));
console.log('PASS: render, mandatory bound research audit, stale/tampered/incomplete audit rejection, soft editorial targets, shared roundup evidence, balanced HTML, section order, table counts, checksums, duplicate rejection, URL rejection and unavailable slots');
console.log(validation.trim());
